### ISSUE TITLE
PS 1.6 Sürümü, Guest hesabı ile ödeme eksik field hatası

### ISSUE THREAD

**Issue by metineren** [kahvedigital/iyzico-prestashop#6]
PS 1.6 sürümü için, Guest ödeme sayfasında ContactName gönderilmesi zorunludur hatası veriyor.

iyzicocheckoutform.php içerisinde, 349. satırda yer alan 

`if ($params['cookie']->is_guest == 1)`

 statement içerisine aşağıdaki satırı ekleyerek fixledim. Siz de lütfen güncelleyin 👍 

`
$shipping_address->setContactName($guest_user_detail[0]['firstname'] . ' ' . $guest_user_detail[0]['lastname']);
`

**Comment by kahvedigital** [comment]
Harun selam Opencart 3.0 versiyonu çıktı bunun için github da bize repo oluşturmanı rica edeceğiz geliştirmemiz tamamlanmak üzere. 13.07.2017, 17:40, "Harun Akgün" <notifications@github.com>:Assigned #6 to @kahvedigital.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.   -- Best regards

**Comment by heheok** [comment]
@kahvedigital bu sorun çözüldü mü?

**Comment by kahvedigital** [comment]
@heheok Sorunu test edip eksik olan setContactName parametresini ekledik.
